'use client'
// READ-ONLY in Phase 2.
// Phase 2 only displays existing FieldDecision records.
// Cross-validation write logic is Phase 5.
import type { FieldDecision } from '@/generated/prisma/client'
import { ConfidenceBadge } from './ConfidenceBadge'
import type { FieldConfidenceValue } from '@/types/bank.types'

interface Props { decisions: FieldDecision[] }

export function RulesDecisionTab({ decisions }: Props) {
  if (!decisions.length) {
    return (
      <div className="card" style={{ textAlign: 'center', padding: '48px 24px' }}>
        <p style={{ color: 'var(--color-text-muted)', fontFamily: 'var(--font-playfair)', fontSize: 18, marginBottom: 8 }}>
          No Rules Decisions yet
        </p>
        <p style={{ color: 'var(--color-text-muted)', fontSize: 14 }}>
          Rules decisions are generated by the cross-validation engine (Phase 5).
          They will appear here once evidence has been collected and validated.
        </p>
      </div>
    )
  }

  return (
    <div>
      <div style={{ marginBottom: 16, padding: '10px 16px', background: 'var(--color-accent-subtle)', borderRadius: 'var(--radius-md)', fontSize: 13, color: 'var(--color-text-muted)' }}>
        📖 Read-only — Rules decisions are generated by the cross-validation engine (Phase 5). Human overrides require override_reason.
      </div>
      <div className="table-scroll-wrap">
        <table>
          <thead>
            <tr>
              <th>Field</th>
              <th>Final Value</th>
              <th>Type</th>
              <th>Confidence</th>
              <th>Decision Basis</th>
              <th>Overridden</th>
            </tr>
          </thead>
          <tbody>
            {decisions.map(d => (
              <tr key={d.id}>
                <td style={{ fontWeight: 500 }}>{d.field_name}</td>
                <td>{d.final_value ?? <span style={{ color: 'var(--color-text-muted)' }}>—</span>}</td>
                <td>
                  <span className="status-badge badge-missing" style={{ fontSize: 11 }}>
                    {d.value_type}
                  </span>
                </td>
                <td><ConfidenceBadge value={d.confidence as FieldConfidenceValue} /></td>
                <td style={{ maxWidth: 280, fontSize: 13, color: 'var(--color-text-secondary)' }}>
                  {d.decision_basis}
                </td>
                <td>
                  {d.human_overridden
                    ? <span className="status-badge badge-conflict">Overridden</span>
                    : <span style={{ color: 'var(--color-text-muted)' }}>—</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
